import type { Post } from "../types/posts";

export const POSTS: Post[] = [
    {
        id: 1,
        username: "alice",
        profile_pic: "https://randomuser.me/api/portraits/women/1.jpg",
        image_url: "https://cdn.pixabay.com/photo/2016/08/11/23/48/mountains-1587287_1280.jpg",
        caption: "Beautiful sunset today! 🌅 #nature #sunset",
        likes: 124,
        comments: 12,
        timestamp: "2 hours ago",
    },
    {
        id: 2,
        username: "bob",
        profile_pic: "https://randomuser.me/api/portraits/men/2.jpg",
        image_url: "https://cdn.pixabay.com/photo/2017/02/01/22/02/mountain-landscape-2031539_1280.jpg",
        caption: "Beach vibes 🏖️",
        likes: 89,
        comments: 5,
        timestamp: "5 hours ago",
    },
    {
        id: 3,
        username: "charlie",
        profile_pic: "https://randomuser.me/api/portraits/men/3.jpg",
        image_url: "https://cdn.pixabay.com/photo/2015/12/01/20/28/road-1072823_1280.jpg",
        caption: "Long road ahead 🛣️",
        likes: 234,
        comments: 18,
        timestamp: "1 day ago",
    },
    {
        id: 4,
        username: "danielle",
        profile_pic: "https://randomuser.me/api/portraits/women/4.jpg",
        image_url: "https://cdn.pixabay.com/photo/2016/08/11/23/48/mountains-1587287_1280.jpg",
        caption: "Mountain adventure! ⛰️",
        likes: 156,
        comments: 9,
        timestamp: "1 day ago",
    },
    {
        id: 5,
        username: "eve",
        profile_pic: "https://randomuser.me/api/portraits/women/5.jpg",
        image_url: "https://cdn.pixabay.com/photo/2017/02/01/22/02/mountain-landscape-2031539_1280.jpg",
        caption: "Peaceful morning 🌄",
        likes: 201,
        comments: 15,
        timestamp: "2 days ago",
    },
    {
        id: 6,
        username: "frank",
        profile_pic: "https://randomuser.me/api/portraits/men/6.jpg",
        image_url: "https://cdn.pixabay.com/photo/2016/08/11/23/48/mountains-1587287_1280.jpg",
        caption: "Nature is amazing 🌲",
        likes: 178,
        comments: 11,
        timestamp: "2 days ago",
    },
];

